#!/usr/bin/env bash
# Generate the releases repo's root README.md from the per-release changelog files.
#
# One argument: the directory holding the release files
# (`<version>-<bump>-<channel>.md`, each starting with a heading like
# `# 0.1.14 (patch, beta) - 2026-08-20`). README text is written to stdout.
#
# Releases are listed newest-first and split into a Stable group and a Beta group,
# each entry a collapsible <details> so the page stays short and a reader can jump to
# the channel they care about. The channel and bump come from each file's heading, so
# renaming a promoted beta's file to `-stable` moves it between groups automatically.
#
# This file is the single source for the layout; the release workflow and the one-time
# backfill both call it, so there is one place to change the format.
set -euo pipefail

dir="${1:?usage: gen-releases-readme.sh <changelog-dir>}"

# Collect "version|bump|channel|date|path", one per release file, skipping the
# convention docs that are not releases.
rows=""
for f in "$dir"/*.md; do
  base=$(basename "$f")
  case "$base" in
    README.md | TEMPLATE.md | next.md) continue ;;
  esac
  head1=$(head -1 "$f")
  # `# <ver> (<bump>, <channel>) - <date>`
  if [[ "$head1" =~ ^#[[:space:]]+([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]+\((patch|minor|major),[[:space:]]*(beta|stable)\)[[:space:]]+-[[:space:]]+(.+)$ ]]; then
    ver="${BASH_REMATCH[1]}"; bump="${BASH_REMATCH[2]}"; chan="${BASH_REMATCH[3]}"; date="${BASH_REMATCH[4]}"
    rows+="${ver}|${bump}|${chan}|${date}|${f}"$'\n'
  else
    echo "gen-releases-readme: skipping $base (no parseable heading)" >&2
  fi
done

# Body of one release file: everything after the heading, with the `### Internal`
# section dropped (kept for the record in the file, never shown to users) and blank
# edges trimmed.
emit_body() {
  awk 'NR==1 && /^# /{next} 1' "$1" \
    | awk '/^#{1,6}[[:space:]]+[Ii]nternal[[:space:]]*$/{s=1;next} /^#{1,6}[[:space:]]/{s=0} !s' \
    | sed -e '/./,$!d' | tac | sed -e '/./,$!d' | tac
}

# One <details> block per release, newest version first.
emit_group() {
  want="$1"; any=0
  while IFS='|' read -r ver bump chan date path; do
    [ -n "$ver" ] || continue
    [ "$chan" = "$want" ] || continue
    any=1
    printf '<details>\n'
    printf '<summary><strong>v%s</strong> (%s) - %s</summary>\n\n' "$ver" "$bump" "$date"
    emit_body "$path"
    printf '\n</details>\n\n'
  done < <(printf '%s' "$rows" | sort -t'|' -k1,1 -V -r)
  return $((1 - any))
}

printf '# RoverTools releases\n\n'
printf 'Public release feed for the RoverTools Smart Clipboard desktop app - signed bundles and update manifests only, no source. Every release and its notes are below; the full per-release files live in [`changelog/`](changelog/).\n\n'
printf 'Site and documentation: [orange-copy-paste-app.pages.dev](https://orange-copy-paste-app.pages.dev) - what the app does, how to install it, and how each screen works.\n\n'
printf 'Two channels: **stable** reaches everyone, **beta** reaches only installs opted into beta versions (Settings, Updates, Get beta versions). A release stays in its group until it is promoted.\n\n'
printf '<!-- RELEASES:START (generated by .github/scripts/gen-releases-readme.sh - do not edit by hand) -->\n\n'

if printf '%s' "$rows" | grep -q '|stable|'; then
  printf '## Stable\n\n'
  emit_group stable || true
fi
if printf '%s' "$rows" | grep -q '|beta|'; then
  printf '## Beta\n\n'
  emit_group beta || true
fi

printf '<!-- RELEASES:END -->\n'
